### ISSUE TITLE
Can't use easyhid on macOS Ventura 13.1

### ISSUE THREAD

**Issue by misz11** [ahtn/python-easyhid#5]
After installing easyhid with the special installing procedure.
I have tried to open a bug at hidapi site, but they say it's an easyhid issue.

Here's the problem:
`Traceback (most recent call last):
  File "/Users/admin/local/examples/basicExample.py", line 5, in <module>
    success = pyspacemouse.open()
  File "/Users/admin/opt/anaconda3/envs/rt39/lib/python3.9/site-packages/pyspacemouse/pyspacemouse.py", line 703, in open
    all_devices = list_devices()
  File "/Users/admin/opt/anaconda3/envs/rt39/lib/python3.9/site-packages/pyspacemouse/pyspacemouse.py", line 643, in list_devices
    hid = Enumeration()
  File "/Users/admin/opt/anaconda3/envs/rt39/lib/python3.9/site-packages/easyhid/easyhid.py", line 366, in __init__
    self.device_list = _hid_enumerate(vid, pid)
  File "/Users/admin/opt/anaconda3/envs/rt39/lib/python3.9/site-packages/easyhid/easyhid.py", line 428, in _hid_enumerate
    start = hidapi.hid_enumerate(vendor_id, product_id)
  File "/Users/admin/opt/anaconda3/envs/rt39/lib/python3.9/site-packages/cffi/api.py", line 912, in __getattr__
    make_accessor(name)
  File "/Users/admin/opt/anaconda3/envs/rt39/lib/python3.9/site-packages/cffi/api.py", line 908, in make_accessor
    accessors[name](name)
  File "/Users/admin/opt/anaconda3/envs/rt39/lib/python3.9/site-packages/cffi/api.py", line 838, in accessor_function
    value = backendlib.load_function(BType, name)
AttributeError: function/symbol 'hid_enumerate' not found in library '<None>': dlsym(RTLD_DEFAULT, hid_enumerate): symbol not found
`
I'm using version: 0.0.10
`pip show easyhid
Name: easyhid
Version: 0.0.10
Summary: A simple interface to the HIDAPI library.
Home-page: http://github.com/ahtn/python-easyhid
Author: jem
Author-email: jem@seethis.link
License: MIT
Location: /Users/admin/opt/anaconda3/envs/rt39/lib/python3.9/site-packages
Requires: cffi
Required-by: hat-spacemouse, pyspacemouse
`

What can I do?

**Comment by misz11** [comment]
After installing easyhid with the special installing procedure.
I have tried to open a bug at hidapi site, but they say it's an easyhid issue.

Here's the problem:
`Traceback (most recent call last):
  File "/Users/admin/local/examples/basicExample.py", line 5, in <module>
    success = pyspacemouse.open()
  File "/Users/admin/opt/anaconda3/envs/rt39/lib/python3.9/site-packages/pyspacemouse/pyspacemouse.py", line 703, in open
    all_devices = list_devices()
  File "/Users/admin/opt/anaconda3/envs/rt39/lib/python3.9/site-packages/pyspacemouse/pyspacemouse.py", line 643, in list_devices
    hid = Enumeration()
  File "/Users/admin/opt/anaconda3/envs/rt39/lib/python3.9/site-packages/easyhid/easyhid.py", line 366, in __init__
    self.device_list = _hid_enumerate(vid, pid)
  File "/Users/admin/opt/anaconda3/envs/rt39/lib/python3.9/site-packages/easyhid/easyhid.py", line 428, in _hid_enumerate
    start = hidapi.hid_enumerate(vendor_id, product_id)
  File "/Users/admin/opt/anaconda3/envs/rt39/lib/python3.9/site-packages/cffi/api.py", line 912, in __getattr__
    make_accessor(name)
  File "/Users/admin/opt/anaconda3/envs/rt39/lib/python3.9/site-packages/cffi/api.py", line 908, in make_accessor
    accessors[name](name)
  File "/Users/admin/opt/anaconda3/envs/rt39/lib/python3.9/site-packages/cffi/api.py", line 838, in accessor_function
    value = backendlib.load_function(BType, name)
AttributeError: function/symbol 'hid_enumerate' not found in library '<None>': dlsym(RTLD_DEFAULT, hid_enumerate): symbol not found
`
I'm using version: 0.0.10
`pip show easyhid
Name: easyhid
Version: 0.0.10
Summary: A simple interface to the HIDAPI library.
Home-page: http://github.com/ahtn/python-easyhid
Author: jem
Author-email: jem@seethis.link
License: MIT
Location: /Users/misz/opt/anaconda3/envs/rt39/lib/python3.9/site-packages
Requires: cffi
Required-by: hat-spacemouse, pyspacemouse
`
